from django.urls import path, include
from rest_framework.routers import DefaultRouter
from person.views import PersonViewSet, LoginAPIView, LogoutAPIView

# Initialize a DefaultRouter for automatic URL routing of viewsets
router = DefaultRouter()
router.register(
    r"person", PersonViewSet
)  # Registers the PersonViewSet under the 'person' endpoint

# Define the main URL patterns for the application
urlpatterns = [
    path(
        "", include(router.urls)
    ),  # Includes all routes generated by the DefaultRouter
]

# Additional standalone API endpoints (not handled by the router)
endpoints = [
    path(
        "login/", LoginAPIView.as_view(), name="login_api"
    ),  # Endpoint for person login
    path(
        "logout/", LogoutAPIView.as_view(), name="logout_api"
    ),  # Endpoint for person logout
]

# Combine the router-generated URLs with additional API endpoints
urlpatterns += endpoints
